use std::{any::Any, collections::VecDeque, fmt::Debug};

use rspack_error::{Result, error};
use rspack_util::ext::AsAny;
use tokio::task::{self, JoinSet};
use tracing::Instrument;

/// Result returned by task
///
/// The success value will contain the tasks that should run next
pub type TaskResult<Ctx> = Result<Vec<Box<dyn Task<Ctx>>>>;

/// Task type
pub enum TaskType {
  /// Main Task
  Main,
  /// Background Task
  Background,
}

/// Used for define tasks
///
/// See test for more example
#[async_trait::async_trait]
pub trait Task<Ctx>: Debug + Send + Any + AsAny {
  /// Return the task type
  ///
  /// Return `TaskType::Main` will run `self::main_run`
  /// Return `TaskType::Background` will run `self::background_run`
  fn get_task_type(&self) -> TaskType;

  /// can be running in main thread
  async fn main_run(self: Box<Self>, _context: &mut Ctx) -> TaskResult<Ctx> {
    unreachable!();
  }

  /// can be running in background thread
  async fn background_run(self: Box<Self>) -> TaskResult<Ctx> {
    unreachable!();
  }
}

struct TaskLoop<Ctx> {
  /// Main tasks run sequentially in the queue
  main_task_queue: VecDeque<Box<dyn Task<Ctx>>>,
  /// Background tasks currently running on the Tokio runtime.
  /// JoinSet lets the task loop await them directly without an extra result channel.
  background_tasks: JoinSet<TaskResult<Ctx>>,
}

impl<Ctx: 'static> TaskLoop<Ctx> {
  fn new(init_main_tasks: Vec<Box<dyn Task<Ctx>>>) -> Self {
    Self {
      main_task_queue: VecDeque::from(init_main_tasks),
      background_tasks: JoinSet::new(),
    }
  }

  async fn run_task_loop(
    &mut self,
    ctx: &mut Ctx,
    init_background_tasks: Vec<Box<dyn Task<Ctx>>>,
  ) -> Result<()> {
    for background_task in init_background_tasks {
      self.spawn_background(background_task);
    }

    loop {
      // Drain all currently available background results to populate the queue.
      // Batch processing reduces loop overhead and ensures the main thread has a more complete view of pending work.
      while let Some(res) = self.background_tasks.try_join_next() {
        self.handle_background_task_result(res).await?;
        task::coop::consume_budget().await;
      }

      let task = self.main_task_queue.pop_front();

      // If there are no main tasks and no background tasks, we are finished.
      if task.is_none() {
        if self.background_tasks.is_empty() {
          return Ok(());
        }

        // Wait for at least one background task to finish.
        let res = self
          .background_tasks
          .join_next()
          .await
          .expect("should recv success");
        self.handle_background_task_result(res).await?;
        continue;
      }

      if let Some(task) = task {
        debug_assert!(matches!(task.get_task_type(), TaskType::Main));
        // Use LIFO/DFS (to_front = true) for tasks generated by a Main task.
        // This ensures a specific module's build chain (Factorize -> Add -> Build) is completed as fast as possible,
        // saturating background worker threads sooner and reducing overall latency.
        self
          .handle_task_result(task.main_run(ctx).await, true)
          .await?;
        task::coop::consume_budget().await;
      }
    }
  }

  /// Merge task result
  ///
  /// `to_front` determines if Main tasks are pushed to the front (LIFO/DFS) or back (FIFO/BFS) of the queue.
  async fn handle_task_result(&mut self, result: TaskResult<Ctx>, to_front: bool) -> Result<()> {
    match result {
      Ok(tasks) => {
        if to_front {
          // Iterate in reverse to preserve original order when using push_front
          for task in tasks.into_iter().rev() {
            match task.get_task_type() {
              TaskType::Main => self.main_task_queue.push_front(task),
              TaskType::Background => self.spawn_background(task),
            }
            task::coop::consume_budget().await;
          }
        } else {
          for task in tasks {
            match task.get_task_type() {
              TaskType::Main => self.main_task_queue.push_back(task),
              TaskType::Background => self.spawn_background(task),
            }
            task::coop::consume_budget().await;
          }
        }
        Ok(())
      }
      Err(e) => Err(e),
    }
  }

  async fn handle_background_task_result(
    &mut self,
    result: std::result::Result<TaskResult<Ctx>, task::JoinError>,
  ) -> Result<()> {
    match result {
      Ok(result) => self.handle_task_result(result, false).await,
      Err(err) if err.is_panic() => std::panic::resume_unwind(err.into_panic()),
      Err(err) => Err(error!("background task failed to join: {err}")),
    }
  }

  fn spawn_background(&mut self, task: Box<dyn Task<Ctx>>) {
    rspack_tasks::spawn_in_compiler_context_on_join_set(
      &mut self.background_tasks,
      async move { task.background_run().await }.in_current_span(),
    );
  }
}

pub async fn run_task_loop<Ctx: 'static>(
  ctx: &mut Ctx,
  init_tasks: Vec<Box<dyn Task<Ctx>>>,
) -> Result<()> {
  let (background_tasks, main_tasks) = init_tasks
    .into_iter()
    .partition(|task| matches!(task.get_task_type(), TaskType::Background));
  let mut task_loop = TaskLoop::new(main_tasks);
  task_loop.run_task_loop(ctx, background_tasks).await
}

#[cfg(test)]
mod test {
  use rspack_error::error;
  use rspack_tasks::within_compiler_context_for_testing;

  use super::*;

  #[derive(Default)]
  struct Context {
    call_sync_task_count: u32,
    max_sync_task_call: u32,
    sync_return_error: bool,
    async_return_error: bool,
  }

  #[derive(Debug)]
  struct SyncTask;
  #[async_trait::async_trait]
  impl Task<Context> for SyncTask {
    fn get_task_type(&self) -> TaskType {
      TaskType::Main
    }
    async fn main_run(self: Box<Self>, context: &mut Context) -> TaskResult<Context> {
      if context.sync_return_error {
        return Err(error!("throw sync error"));
      }

      let async_return_error = context.async_return_error;
      context.call_sync_task_count += 1;
      if context.call_sync_task_count < context.max_sync_task_call {
        return Ok(vec![
          Box::new(AsyncTask { async_return_error }),
          Box::new(AsyncTask { async_return_error }),
        ]);
      }
      Ok(vec![])
    }
  }

  #[derive(Debug)]
  struct AsyncTask {
    async_return_error: bool,
  }
  #[async_trait::async_trait]
  impl Task<Context> for AsyncTask {
    fn get_task_type(&self) -> TaskType {
      TaskType::Background
    }
    async fn background_run(self: Box<Self>) -> TaskResult<Context> {
      tokio::time::sleep(std::time::Duration::from_millis(10)).await;
      if self.async_return_error {
        Err(error!("throw async error"))
      } else {
        Ok(vec![Box::new(SyncTask)])
      }
    }
  }

  #[derive(Debug)]
  struct PanicAsyncTask;
  #[async_trait::async_trait]
  impl Task<Context> for PanicAsyncTask {
    fn get_task_type(&self) -> TaskType {
      TaskType::Background
    }

    async fn background_run(self: Box<Self>) -> TaskResult<Context> {
      panic!("panic async task");
    }
  }

  #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
  async fn test_run_task_loop() {
    within_compiler_context_for_testing(async {
      let mut context = Context {
        call_sync_task_count: 0,
        max_sync_task_call: 4,
        sync_return_error: false,
        async_return_error: false,
      };
      let res = run_task_loop(
        &mut context,
        vec![Box::new(AsyncTask {
          async_return_error: false,
        })],
      )
      .await;
      assert!(res.is_ok(), "task loop should be run success");
      assert_eq!(context.call_sync_task_count, 7);

      let mut context = Context {
        call_sync_task_count: 0,
        max_sync_task_call: 4,
        sync_return_error: true,
        async_return_error: false,
      };
      let res = run_task_loop(
        &mut context,
        vec![Box::new(AsyncTask {
          async_return_error: false,
        })],
      )
      .await;
      assert!(
        format!("{res:?}").contains("throw sync error"),
        "should return sync error"
      );
      assert_eq!(context.call_sync_task_count, 0);

      let mut context = Context {
        call_sync_task_count: 0,
        max_sync_task_call: 4,
        sync_return_error: false,
        async_return_error: true,
      };
      let res = run_task_loop(
        &mut context,
        vec![Box::new(AsyncTask {
          async_return_error: false,
        })],
      )
      .await;
      assert!(
        format!("{res:?}").contains("throw async error"),
        "should return async error"
      );
      assert_eq!(context.call_sync_task_count, 1);
    })
    .await;
  }

  #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
  #[should_panic(expected = "panic async task")]
  async fn test_run_task_loop_propagates_background_panic() {
    within_compiler_context_for_testing(async {
      let mut context = Context::default();
      let _ = run_task_loop(&mut context, vec![Box::new(PanicAsyncTask)]).await;
    })
    .await;
  }
}
